[/]
animate-appicon-hover-animation-extent={'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}
dot-position='BOTTOM'
extension-version=72
hide-overview-on-startup=true
hotkeys-overlay-combo='TEMPORARILY'
panel-anchors='{"GSM-302MAFCEST47":"MIDDLE","GSM-303MAKRBUA97":"MIDDLE"}'
panel-element-positions='{}'
panel-lengths='{}'
panel-positions='{}'
panel-sizes='{}'
prefs-opened=false
window-preview-title-position='TOP'
